on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  create-and-upload-index:
    # prevent forks of this repo from uploading lsif indexes
    if: github.repository == 'prestonator/my-scraper'
    runs-on: ubuntu-latest
    container: sourcegraph/scip-typescript:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Generate index
        run: scip-typescript index
      - name: Upload index
        run: src code-intel upload -root='' -repo='github.com/prestonator/my-scraper' -github-token='${{ secrets.TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.com/
